### ISSUE TITLE
Private playlist download error

### ISSUE THREAD

**Issue by superMDMArio** [devlocalhost/pyspodl#1]
thanks for script. all good in download song function, but playlist download wont work here.

Traceback (most recent call last):
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 424, in <module>
    main()
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 341, in main
    isvalid(TOKEN)
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 82, in isvalid
    main()
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 358, in main
    downloader(uri, EMAIL, PASSWD, TOKEN)
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 305, in downloader
    main()
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 388, in main
    playlist_download(playid, TOKEN, EMAIL, PASSWD)
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 233, in playlist_download
    target = info['tracks']['total']
KeyError: 'tracks'

**Comment by superMDMArio** [comment]
after update account and get token by gettoken.py

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 424, in <module>
    main()
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 341, in main
    isvalid(TOKEN)
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 82, in isvalid
    main()
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 396, in main
    writedetails()
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 327, in writedetails
    main()
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 388, in main
    playlist_download(playid, TOKEN, EMAIL, PASSWD)
  File "/Users/myuser/Downloads/pyspodl-main/main.py", line 230, in playlist_download
    resp = get(f'https://api.spotify.com/v1/playlists/{playlist_id}', headers=headr).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

**Comment by superMDMArio** [comment]
work now!


I was trying to download a private playlist! lol

**Comment by devlocalhost** [comment]
i see. ill try to find a fix about this issue, if possible. ill update if i find anything. if not, then sorry
